---
title: "dawsondiaz"
author: "dawsondiaz"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Libraries

```{r message=FALSE, warning=FALSE}
#install.packages("tidyverse")
#install.packages("naniar")
#install.packages("gapminder")
#install.packages("knitr")
#install.packages("kableExtra")


library(tidyverse)
library(naniar)
library(gapminder)
library(knitr)
library(kableExtra)
```


## R Markdown
```{r}
cdc_raw <- readr::read_csv("cdc-113-ICD10.csv")
```

```{r}
glimpse(cdc_raw)
```


```{r}
glimpse(cdc)
```


## Clean Data

```{r}
cdc <- cdc_raw %>% 
  #remove redundant, uncessary columns
  select(-c("Notes", "Year Code", "State Code", "Ten-Year Age Groups")) %>% 

  #remove several rows with NA values at bottom of data frame
  na.omit() %>% 
  
  #NA in these data sets is coded as "Unreliable"
  na_if("Unreliable") %>%  
  
  #rename column names 
  dplyr::rename( 
    state=State,
    deaths=Deaths,
    year=Year,
    age_group= "Ten-Year Age Groups Code",
    population= Population,
    crude_rate = "Crude Rate",
    cause_of_death = "ICD-10 113 Cause List",
    cause_of_death_code = "ICD-10 113 Cause List Code")
  
```


```{r}
change characters to factors??
```



```{r}
cdc %>% 
  select(year, state, cause_of_death, deaths) %>%
  filter(cause_of_death == '#Human immunodeficiency virus (HIV) disease (B20-B24)') %>% 
  group_by(year) %>% 
  summarise(
    total_deaths_HIV = sum(deaths)) %>% 
  ggplot(aes(x=year, y=total_deaths_HIV))+geom_line()

```

  group_by(year) %>% 
  filter(cause_of_death == "	
#Human immunodeficiency virus (HIV) disease (B20-B24)") %>% 
  summarise(
    deaths = sum(deaths)
    
  )



